import os

translations = {
    # .label() translations (475 items)
    "API Key": "API 密钥",
    "API token": "API 令牌",
    "ASN Index": "ASN 索引",
    "ASN Name Index": "ASN 名称索引",
    "ASN URLs": "ASN URL",
    "ASN/Geo Source": "ASN/地理位置来源",
    "Abuse attempts": "滥用尝试",
    "Access Key": "访问密钥",
    "Access Tokens": "访问令牌",
    "Account by Name": "按名称查找账户",
    "Account key": "账户密钥",
    "Address": "地址",
    "Address Books": "通讯录",
    "Alarm Template": "提醒模板",
    "Alert Id": "告警 ID",
    "Alert condition": "告警条件",
    "Allow Directory Queries": "允许目录查询",
    "Allow External Recipients": "允许外部收件人",
    "Allow Relaying": "允许中继",
    "Allow anonymous registration": "允许匿名注册",
    "Allow plain text authentication": "允许明文认证",
    "Allow undeclared capabilities": "允许未声明的功能",
    "Allowed Mechanisms": "允许的认证机制",
    "Allowed endpoints": "允许的端点",
    "Alpha": "Alpha",
    "Anonymous": "匿名",
    "Assisted Discovery": "辅助发现",
    "Attachment Size": "附件大小",
    "Attempt Interval": "尝试间隔",
    "Auth code": "授权码",
    "Auth failures": "认证失败",
    "Auth secret": "认证密钥",
    "Auth token": "认证令牌",
    "Auth username": "认证用户名",
    "Authenticated": "已认证",
    "Authentication-Results": "认证结果",
    "Auto-update webadmin": "自动更新管理面板",
    "Automatically Add Invitations": "自动添加邀请",
    "Automatically update spam filter rules": "自动更新垃圾邮件过滤规则",
    "Backlog": "积压",
    "Base DN": "基础 DN",
    "Base URL": "基础 URL",
    "Bearer Token": "Bearer 令牌",
    "Beta": "Beta",
    "Bind DN": "绑定 DN",
    "Bind DN template": "绑定 DN 模板",
    "Bind Secret": "绑定密钥",
    "Bind addresses": "绑定地址",
    "Blob stores": "Blob 存储",
    "Body": "正文",
    "Buffered writes": "缓冲写入",
    "Bytes Limit": "字节限制",
    "CPU": "CPU",
    "Cache size": "缓存大小",
    "Calculate Metrics": "计算指标",
    "Calendar Alerts": "日历提醒",
    "Calendar Events": "日历事件",
    "Capacity": "容量",
    "Catch-all": "全部捕获",
    "Categories": "分类",
    "Category Index": "分类索引",
    "Certificate Id": "证书 ID",
    "Challenge type": "验证类型",
    "Changes": "变更",
    "Changes history": "变更历史",
    "Chunking": "分块",
    "Client Capacity": "客户端容量",
    "Cluster file": "集群文件",
    "Collect frequency": "采集频率",
    "Command": "命令",
    "Compression": "压缩",
    "Concurrent": "并发",
    "Concurrent Requests": "并发请求",
    "Confidence": "置信度",
    "Confidence Index": "置信度索引",
    "Connect": "连接",
    "Connection Timeout": "连接超时",
    "Consumer key": "消费者密钥",
    "Contact Cards": "联系人卡片",
    "Contact Email": "联系邮箱",
    "Contacts": "联系人",
    "Container": "容器",
    "Contents": "内容",
    "Coordinator": "协调器",
    "Count": "数量",
    "Country Index": "国家索引",
    "Create Timeout": "创建超时",
    "DANE": "DANE",
    "DATA": "DATA",
    "DKIM Signatures": "DKIM 签名",
    "DNS Provider": "DNS 提供商",
    "DNS Servers": "DNS 服务器",
    "DSN": "DSN",
    "Data Center Id": "数据中心 ID",
    "Database": "数据库",
    "Date": "日期",
    "Dead Property": "死属性",
    "Default Display Name": "默认显示名称",
    "Default Expiry": "默认过期时间",
    "Default Href Name": "默认链接名称",
    "Default Language": "默认语言",
    "Default Prefix": "默认前缀",
    "Default Subject": "默认主题",
    "Default certificate": "默认证书",
    "Default logo URL": "默认 Logo URL",
    "Default provider": "默认提供商",
    "Deliver By": "投递期限",
    "Delivered-To": "投递至",
    "Delivery Threads": "投递线程数",
    "Directory Id": "目录 ID",
    "Directory URL": "目录 URL",
    "Disable Capabilities": "禁用功能",
    "Disabled Ciphersuites": "禁用的加密套件",
    "Disabled Events": "禁用的事件",
    "Disabled Metrics": "禁用的指标",
    "Disabled Protocols": "禁用的协议",
    "Discard threshold": "丢弃阈值",
    "Disk Quota": "磁盘配额",
    "Do not classify emails from contacts as spam": "不将联系人邮件归为垃圾邮件",
    "Do not classify trusted email replies as spam": "不将可信回复归为垃圾邮件",
    "Domain Checks": "域名检查",
    "Duration": "持续时间",
    "E-mail Address": "邮箱地址",
    "E-mail Aliases": "邮箱别名",
    "E-mail Checks": "邮箱检查",
    "E-mail Size": "邮件大小",
    "E-mail default": "邮箱默认值",
    "E-mail field": "邮箱字段",
    "E-mails by Name": "按名称查找邮箱",
    "EHLO": "EHLO",
    "EHLO Hostname": "EHLO 主机名",
    "EXPN": "EXPN",
    "Email Identities": "邮件身份",
    "Email Submissions": "邮件提交",
    "Enable Calendar Searching": "启用日历搜索",
    "Enable Contacts Searching": "启用联系人搜索",
    "Enable E-mail Alarms": "启用邮件提醒",
    "Enable EDNS": "启用 EDNS",
    "Enable Email Searching": "启用邮件搜索",
    "Enable HTTP RSVP": "启用 HTTP RSVP",
    "Enable HTTP Strict Transport Security": "启用 HTTP 严格传输安全",
    "Enable LLM classifier": "启用 LLM 分类器",
    "Enable Pyzor": "启用 Pyzor",
    "Enable Pyzor classifier": "启用 Pyzor 分类器",
    "Enable Scheduling": "启用调度",
    "Enable Tracing Searching": "启用追踪搜索",
    "Enable encryption at rest": "启用静态加密",
    "Enable endpoint": "启用端点",
    "Enable form submissions": "启用表单提交",
    "Enable list": "启用列表",
    "Enable metrics history": "启用指标历史",
    "Enable rule": "启用规则",
    "Enable spam filtering": "启用垃圾邮件过滤",
    "Enable the DNSBL server": "启用 DNSBL 服务器",
    "Enable this tracer": "启用此追踪器",
    "Enable tracing history": "启用追踪历史",
    "Encrypt on append": "追加时加密",
    "Entry length": "条目长度",
    "Error wait": "错误等待",
    "Event Id": "事件 ID",
    "Events": "事件",
    "Expiration Strategy": "过期策略",
    "Expire after": "过期时间",
    "Expiry": "过期",
    "Explanation Index": "解释索引",
    "Export logs": "导出日志",
    "Export spans": "导出跨度",
    "Extension": "扩展",
    "FTS Indexing": "全文搜索索引",
    "File Nodes": "文件节点",
    "Files": "文件",
    "Format": "格式",
    "From": "发件人",
    "From E-mail": "发件邮箱",
    "Future Release": "延迟发送",
    "Geolocation URLs": "地理位置 URL",
    "Get": "获取",
    "Greeting": "问候语",
    "Gzipped": "Gzip 压缩",
    "HMAC Key": "HMAC 密钥",
    "HTTP Authorization": "HTTP 授权",
    "HTTP RSVP Expiration": "HTTP RSVP 过期时间",
    "HTTP RSVP URL": "HTTP RSVP URL",
    "HTTP banned paths": "HTTP 禁止路径",
    "Handshake Timeout": "握手超时",
    "Header Size": "头部大小",
    "Heartbeat": "心跳",
    "Hold samples for": "样本保留时间",
    "Honey Pot field": "蜜罐字段",
    "Hook Id": "Hook ID",
    "Host": "主机",
    "ID": "ID",
    "IP Address(es)": "IP 地址",
    "IP Checks": "IP 检查",
    "IP Resolution": "IP 解析",
    "IPRev Verify": "IPRev 验证",
    "IPv4 Records": "IPv4 记录",
    "IPv4 Zone": "IPv4 区域",
    "IPv6 Records": "IPv6 记录",
    "IPv6 Zone": "IPv6 区域",
    "Idle": "空闲",
    "Ignore client order": "忽略客户端顺序",
    "Implicit TLS": "隐式 TLS",
    "In-memory stores": "内存存储",
    "Inbox Auto-Expunge": "收件箱自动清除",
    "Includes": "包含",
    "Indexing Batch Size": "索引批量大小",
    "Interval": "间隔",
    "JWT Credentials": "JWT 凭证",
    "Key": "密钥",
    "Key ID": "密钥 ID",
    "Key Index": "密钥索引",
    "Key Prefix": "密钥前缀",
    "L1 Ratio": "L1 比率",
    "L2 (euclidean) normalization": "L2（欧几里得）归一化",
    "L2 Ratio": "L2 比率",
    "Learn ham from address books": "从通讯录学习正常邮件",
    "Learn ham from trusted replies": "从可信回复学习正常邮件",
    "Learn spam from spam traps": "从垃圾邮件陷阱学习垃圾邮件",
    "Level": "级别",
    "License Key": "许可证密钥",
    "Limiter ID": "限制器 ID",
    "Linger": "延迟关闭",
    "List ID": "列表 ID",
    "Listener Id": "监听器 ID",
    "Live Property": "活动属性",
    "Local Domains": "本地域名",
    "Local Variables": "本地变量",
    "Local settings": "本地设置",
    "Logging level": "日志级别",
    "Loitering": "逗留",
    "Lossy mode": "有损模式",
    "MAIL FROM": "MAIL FROM",
    "MAIL-FROM": "MAIL-FROM",
    "MT Priority": "MT 优先级",
    "MTA-STS": "MTA-STS",
    "MTA-STS Records": "MTA-STS 记录",
    "MX Hosts": "MX 主机",
    "MX Patterns (override)": "MX 模式（覆盖）",
    "MX Records": "MX 记录",
    "Machine Id": "机器 ID",
    "Mailboxes": "邮箱",
    "Match Variables": "匹配变量",
    "Max Allowed Packet": "最大允许数据包",
    "Max Auth Errors": "最大认证错误数",
    "Max Concurrent": "最大并发",
    "Max Connections": "最大连接数",
    "Max Depth": "最大深度",
    "Max Errors": "最大错误数",
    "Max Failures": "最大失败数",
    "Max File Size": "最大文件大小",
    "Max Lock Timeout": "最大锁超时",
    "Max Locks Per User": "每用户最大锁数",
    "Max Messages": "最大消息数",
    "Max Reconnects": "最大重连次数",
    "Max Request Size": "最大请求大小",
    "Max Response": "最大响应",
    "Max Results": "最大结果数",
    "Max Retry Delay": "最大重试延迟",
    "Max Shares": "最大共享数",
    "Max Wait": "最大等待时间",
    "Max attempts": "最大尝试次数",
    "Max connections": "最大连接数",
    "Max entries": "最大条目数",
    "Max iCal Attendees": "最大 iCal 参与者数",
    "Max iCal Instances": "最大 iCal 实例数",
    "Max iCal Size": "最大 iCal 大小",
    "Max iTIP Size": "最大 iTIP 大小",
    "Max lifetime": "最大生命周期",
    "Max vCard Size": "最大 vCard 大小",
    "Members by Name": "按名称查找成员",
    "Message": "消息",
    "Message-Id": "消息 ID",
    "Method Calls": "方法调用",
    "Metrics Store": "指标存储",
    "Milter Id": "Milter ID",
    "Min Connections": "最小连接数",
    "Min Wait": "最小等待时间",
    "Min blob size": "最小 Blob 大小",
    "Min. Ham samples": "最小正常邮件样本数",
    "Min. Spam samples": "最小垃圾邮件样本数",
    "Minimum Alarm Interval": "最小提醒间隔",
    "Model Id": "模型 ID",
    "Multi-homed IPs": "多宿主 IP",
    "Multiline entries": "多行条目",
    "Must match sender": "必须匹配发件人",
    "Name Length": "名称长度",
    "Name by E-mail": "按邮箱查找名称",
    "Name default": "名称默认值",
    "Name field": "名称字段",
    "Negative TTL": "负缓存 TTL",
    "Nested Blocks": "嵌套块",
    "Nested Depth": "嵌套深度",
    "Nested Foreach": "嵌套循环",
    "Nested Includes": "嵌套包含",
    "Nested Tests": "嵌套测试",
    "No Echo": "禁止回显",
    "No delay": "无延迟",
    "No-Soliciting": "禁止推销",
    "Node ID": "节点 ID",
    "Notification URIs": "通知 URI",
    "Notify Intervals": "通知间隔",
    "Number of Replicas": "副本数",
    "Number of Shards": "分片数",
    "OVH Endpoint": "OVH 端点",
    "Obtain remote IP from Forwarded header": "从 Forwarded 头获取远程 IP",
    "Outgoing Messages": "外发消息",
    "Override TLS options": "覆盖 TLS 选项",
    "Override proxy networks": "覆盖代理网络",
    "Override socket options": "覆盖套接字选项",
    "PTR Records": "PTR 记录",
    "Parameters": "参数",
    "Passwords by Name": "按名称查找密码",
    "Path": "路径",
    "Permissions": "权限",
    "Permissive CORS policy": "宽松 CORS 策略",
    "Ping Interval": "Ping 间隔",
    "Pipelining": "管道化",
    "Policy Application": "策略应用",
    "Polling interval": "轮询间隔",
    "Pool size": "连接池大小",
    "Positive TTL": "正缓存 TTL",
    "Prefix": "前缀",
    "Preserve Intermediates": "保留中间证书",
    "Primary SQL": "主 SQL",
    "Priority": "优先级",
    "Profile": "配置文件",
    "Prompt": "提示词",
    "Propagation timeout": "传播超时",
    "Protected Headers": "受保护头部",
    "Protocol Version": "协议版本",
    "Protocol version": "协议版本",
    "Proxy networks": "代理网络",
    "Purge Accounts": "清除账户",
    "Purge Frequency": "清除频率",
    "Purge Stores": "清除存储",
    "Push Metrics": "推送指标",
    "Push Subscriptions": "推送订阅",
    "Push interval": "推送间隔",
    "Query": "查询",
    "Quota": "配额",
    "Quota ID": "配额 ID",
    "RBL Records": "RBL 记录",
    "RBL hits": "RBL 命中",
    "RCPT-TO": "RCPT-TO",
    "RSVP Template": "RSVP 模板",
    "Ratio": "比率",
    "Read Buffer Capacity": "读缓冲区容量",
    "Read from replicas": "从副本读取",
    "Read replicas": "读副本",
    "Receive buffer": "接收缓冲区",
    "Received": "已接收",
    "Received-SPF": "Received-SPF",
    "Recipient Rewriting": "收件人重写",
    "Recipients": "收件人",
    "Recycle Timeout": "回收超时",
    "Redirects": "重定向",
    "Refresh token": "刷新令牌",
    "Refresh token renew": "刷新令牌续期",
    "Region": "区域",
    "Reject Non-FQDN": "拒绝非 FQDN",
    "Reject threshold": "拒绝阈值",
    "Renew ACME": "续期 ACME",
    "Renew before": "提前续期",
    "Request": "请求",
    "Request Size": "请求大小",
    "Request Timeout": "请求超时",
    "Requests": "请求数",
    "Require Authentication": "要求认证",
    "Require EHLO": "要求 EHLO",
    "Require TLS": "要求 TLS",
    "Require client registration": "要求客户端注册",
    "Resolver": "解析器",
    "Response headers": "响应头",
    "Retry": "重试",
    "Retry Interval": "重试间隔",
    "Retry Intervals": "重试间隔",
    "Return Path": "返回路径",
    "Return-Path": "Return-Path",
    "Reuse Address": "地址复用",
    "Reuse bind auth connection for search": "复用绑定认证连接进行搜索",
    "Reuse port": "端口复用",
    "Rotate frequency": "轮换频率",
    "Rules URL": "规则 URL",
    "SAS Token": "SAS 令牌",
    "SMTP greeting": "SMTP 问候语",
    "STARTTLS": "STARTTLS",
    "Scanning attempts": "扫描尝试",
    "Scheduling": "调度",
    "Score or action": "评分或动作",
    "Script Size": "脚本大小",
    "Secret Changed": "密钥已更改",
    "Secret Key": "密钥",
    "Security Token": "安全令牌",
    "Send an email": "发送邮件",
    "Send buffer": "发送缓冲区",
    "Sender Rewriting": "发件人重写",
    "Sender is allowed": "允许的发件人",
    "Server Address": "服务器地址",
    "Server Type": "服务器类型",
    "Server hostname": "服务器主机名",
    "Set": "设置",
    "Sharing History": "共享历史",
    "Signature algorithm": "签名算法",
    "Skip header": "跳过头部",
    "Source IPs": "源 IP",
    "Spam Classifier Training": "垃圾邮件分类器训练",
    "Spam filtering": "垃圾邮件过滤",
    "Spam threshold": "垃圾邮件阈值",
    "Storage Account Name": "存储账户名称",
    "Storage backend": "存储后端",
    "Store Id": "存储 ID",
    "String Length": "字符串长度",
    "Sub-addressing": "子地址",
    "Subject Alternative Names": "主题备用名称",
    "Subject default": "主题默认值",
    "Subject field": "主题字段",
    "Subject names": "主题名称",
    "Sublinear term frequency scaling (log1p)": "次线性词频缩放（log1p）",
    "Subscription Capacity": "订阅容量",
    "TLS": "TLS",
    "TLS Certificate": "TLS 证书",
    "TLSA Records": "TLSA 记录",
    "TSIG Algorithm": "TSIG 算法",
    "TTL": "TTL",
    "TXT Records": "TXT 记录",
    "Tag": "标签",
    "Tag name": "标签名称",
    "Thread Pool Size": "线程池大小",
    "Time To Live": "生存时间",
    "To": "收件人",
    "Token": "令牌",
    "Total Files": "文件总数",
    "Total Size": "总大小",
    "Tracer Id": "追踪器 ID",
    "Tracing Store": "追踪存储",
    "Training frequency": "训练频率",
    "Trash auto-expunge": "回收站自动清除",
    "Trigger an event": "触发事件",
    "Trusted Expiry": "可信过期时间",
    "Try TCP on Error": "错误时尝试 TCP",
    "Type of Service": "服务类型",
    "URL": "URL",
    "URL Checks": "URL 检查",
    "URL(s)": "URL",
    "Un-delete period": "恢复期限",
    "Unpack path": "解压路径",
    "Untrusted Expiry": "不可信过期时间",
    "Update URL": "更新 URL",
    "Use ANSI colors": "使用 ANSI 颜色",
    "User code": "用户代码",
    "Username field": "用户名字段",
    "VRFY": "VRFY",
    "Validate email domain": "验证邮箱域名",
    "Value Index": "值索引",
    "Variable Name Length": "变量名长度",
    "Variable Size": "变量大小",
    "Verify": "验证",
    "Virtual Queue": "虚拟队列",
    "WL Count": "白名单计数",
    "Wait Timeout": "等待超时",
    "Webhook Id": "Webhook ID",
    "Write buffer size": "写缓冲区大小",
    "Zone": "区域",
    "iMIP Processing": "iMIP 处理",
    "iMIP Template": "iMIP 模板",

    # .title() translations (176 items)
    "Cluster settings": "集群设置",
    "Column Mappings": "列映射",
    "Configuration": "配置",
    "Connect Stage": "连接阶段",
    "Connection Pools": "连接池",
    "Connection Strategy": "连接策略",
    "Contacts Settings": "联系人设置",
    "DATA Stage": "DATA 阶段",
    "DKIM Reporting": "DKIM 报告",
    "DKIM Signature": "DKIM 签名",
    "DKIM Signing": "DKIM 签名",
    "DKIM Verification": "DKIM 验证",
    "DMARC Aggregate Reporting": "DMARC 聚合报告",
    "DMARC Authentication Failure Reporting": "DMARC 认证失败报告",
    "DMARC Verification": "DMARC 验证",
    "DNS Record Cache": "DNS 记录缓存",
    "DNS Resolver settings": "DNS 解析器设置",
    "DNS Zones": "DNS 区域",
    "DNS settings": "DNS 设置",
    "DNSBL Limits": "DNSBL 限制",
    "DNSBl Configuration": "DNSBL 配置",
    "Data Cache": "数据缓存",
    "Data Store": "数据存储",
    "Default Names": "默认名称",
    "Default Object Quotas": "默认对象配额",
    "Default TLS options": "默认 TLS 选项",
    "Defaults": "默认值",
    "Delayed Delivery Notifications": "延迟投递通知",
    "Delivery Retry Intervals": "投递重试间隔",
    "Delivery Status Notifications (DSN)": "投递状态通知（DSN）",
    "Directory Queries": "目录查询",
    "Drafts": "草稿",
    "Duplicate Extension": "重复扩展",
    "Dynamic Client Registration": "动态客户端注册",
    "E-mail notification": "邮件通知",
    "EHLO Stage": "EHLO 阶段",
    "Email Limits": "邮件限制",
    "Endpoint Authentication": "端点认证",
    "Event Source": "事件源",
    "Event notification": "事件通知",
    "External Account Binding": "外部账户绑定",
    "External Rules": "外部规则",
    "Fallback Administrator": "备用管理员",
    "Field Mappings": "字段映射",
    "Fields": "字段",
    "File Storage": "文件存储",
    "Form submission settings": "表单提交设置",
    "Greylisting": "灰名单",
    "HTTP Base URL": "HTTP 基础 URL",
    "HTTP List Settings": "HTTP 列表设置",
    "HTTP RSVP": "HTTP RSVP",
    "HTTP Security": "HTTP 安全",
    "Hyperparameters": "超参数",
    "Hyperparameters (CCFH)": "超参数（CCFH）",
    "In-Memory Store": "内存存储",
    "Inbound Rate Limiter": "入站速率限制",
    "Inbound Report Analysis": "入站报告分析",
    "Inbox": "收件箱",
    "Index": "索引",
    "JMAP over WebSocket": "JMAP WebSocket",
    "Junk": "垃圾邮件",
    "Key": "密钥",
    "LDAP Authentication Method": "LDAP 认证方法",
    "LDAP Binding": "LDAP 绑定",
    "LDAP Filters": "LDAP 过滤器",
    "LLM Classifier": "LLM 分类器",
    "Licensing": "许可证",
    "Listener settings": "监听器设置",
    "Local Domains": "本地域名",
    "Local configuration keys": "本地配置键",
    "Locking": "锁定",
    "MAIL FROM Stage": "MAIL FROM 阶段",
    "MTA Hook settings": "MTA Hook 设置",
    "MTA-STS Policy": "MTA-STS 策略",
    "MX Resolution": "MX 解析",
    "Mailbox Limits": "邮箱限制",
    "Master User": "主用户",
    "Max Objects": "最大对象数",
    "Max Results": "最大结果数",
    "Message Expiration": "消息过期",
    "Metrics History": "指标历史",
    "Milter settings": "Milter 设置",
    "Network settings": "网络设置",
    "Node Roles": "节点角色",
    "Notification E-mail": "通知邮件",
    "OAuth Settings": "OAuth 设置",
    "Object Attributes": "对象属性",
    "OpenID Connect": "OpenID Connect",
    "OpenTelemetry Push Metrics": "OpenTelemetry 推送指标",
    "Options": "选项",
    "Outbound Rate Limiter": "出站速率限制",
    "Outbound Report Settings": "出站报告设置",
    "Outbound Strategies": "出站策略",
    "Outbound iMIP": "出站 iMIP",
    "Override events": "覆盖事件",
    "Override metrics": "覆盖指标",
    "Parsing Limits": "解析限制",
    "Pools": "连接池",
    "Port scanning ban": "端口扫描封禁",
    "Prometheus Pull Metrics": "Prometheus 拉取指标",
    "Property Limits": "属性限制",
    "Proxy protocol": "代理协议",
    "PubSub": "发布订阅",
    "Push Subscriptions": "推送订阅",
    "Push Timeouts": "推送超时",
    "Pyzor Settings": "Pyzor 设置",
    "Quota": "配额",
    "RCPT TO Stage": "RCPT TO 阶段",
    "Rate Limit": "速率限制",
    "Rate Limiting": "速率限制",
    "Recipient Errors": "收件人错误",
    "Request Limits": "请求限制",
    "Reservoir Sampling": "蓄水池采样",
    "Response": "响应",
    "Response Format": "响应格式",
    "Retrieval": "检索",
    "Route Configuration": "路由配置",
    "Rule Configuration": "规则配置",
    "SMTP Extensions": "SMTP 扩展",
    "SMTP Session Limits": "SMTP 会话限制",
    "SPF Authentication Failure Reporting": "SPF 认证失败报告",
    "SPF Verification": "SPF 验证",
    "Schedule Details": "调度详情",
    "Search Store": "搜索存储",
    "Security Requirements": "安全要求",
    "Sent": "已发送",
    "Server Details": "服务器详情",
    "Shared Folders": "共享文件夹",
    "Sharing Settings": "共享设置",
    "Socket options": "套接字选项",
    "Source IP Addresses": "源 IP 地址",
    "Spam Classifier": "垃圾邮件分类器",
    "Spam Filter Cache": "垃圾邮件过滤缓存",
    "Spam Filter Overrides": "垃圾邮件过滤覆盖",
    "Spam Filter Settings": "垃圾邮件过滤设置",
    "Storage Account": "存储账户",
    "Storage settings": "存储设置",
    "TLS": "TLS",
    "TLS Aggregate Reporting": "TLS 聚合报告",
    "TLS Strategy": "TLS 策略",
    "TLS certificate": "TLS 证书",
    "TLS options": "TLS 选项",
    "TXT Record Format": "TXT 记录格式",
    "Task Polling": "任务轮询",
    "Thread pool": "线程池",
    "Timeouts": "超时",
    "Token Expiration": "令牌过期",
    "Tracer configuration": "追踪器配置",
    "Tracing History": "追踪历史",
    "Training": "训练",
    "Transaction Settings": "事务设置",
    "Trash": "回收站",
    "Triggers": "触发器",
    "Trusted Interpreter": "可信解释器",
    "Trusted Limits": "可信限制",
    "Trusted Sieve Script": "可信 Sieve 脚本",
    "URL Resources": "URL 资源",
    "Untrusted Interpreter": "不可信解释器",
    "Untrusted Limits": "不可信限制",
    "Untrusted Sieve Script": "不可信 Sieve 脚本",
    "Upload Limits": "上传限制",
    "Vacation Extension": "假期扩展",
    "Virtual Queue": "虚拟队列",
    "Web-based Admin": "Web 管理面板",
    "WebDAV Settings": "WebDAV 设置",
    "Webhook settings": "Webhook 设置",

    # .create() translations (~70 items)
    "ACME Providers": "ACME 提供商",
    "AI Models": "AI 模型",
    "ARC": "ARC",
    "ASN & GeoIP": "ASN 和 GeoIP",
    "AUTH stage": "AUTH 阶段",
    "Alerts": "告警",
    "Allowed IPs": "允许的 IP",
    "Analysis": "分析",
    "App Passwords": "应用密码",
    "Automatic Ban": "自动封禁",
    "Blocked IPs": "已封禁 IP",
    "Blocked domains": "已封禁域名",
    "Cache": "缓存",
    "Calendar": "日历",
    "Certificates": "证书",
    "Change Password": "修改密码",
    "Classifier": "分类器",
    "Cluster": "集群",
    "Collaboration": "协作",
    "Connect stage": "连接阶段",
    "Contacts": "联系人",
    "Custom levels": "自定义级别",
    "DATA stage": "DATA 阶段",
    "DKIM": "DKIM",
    "DMARC": "DMARC",
    "DNS": "DNS",
    "DNS blocklists": "DNS 黑名单",
    "DSN": "DSN",
    "Default Folders": "默认文件夹",
    "Defaults": "默认值",
    "Directories": "目录",
    "EHLO stage": "EHLO 阶段",
    "Encryption-at-rest": "静态加密",
    "Enterprise": "企业版",
    "Form submission": "表单提交",
    "HTTP": "HTTP",
    "HTTP lists": "HTTP 列表",
    "IMAP Settings": "IMAP 设置",
    "JMAP": "JMAP",
    "LLM classifier": "LLM 分类器",
    "Logging & Tracing": "日志与追踪",
    "MAIL stage": "MAIL 阶段",
    "MIME Types": "MIME 类型",
    "MTA Hooks": "MTA Hooks",
    "MTA-STS": "MTA-STS",
    "Management": "管理",
    "Message Store": "消息存储",
    "Milter": "Milter",
    "OAuth": "OAuth",
    "OpenID Connect": "OpenID Connect",
    "Protocol Limits": "协议限制",
    "Pyzor": "Pyzor",
    "Quotas": "配额",
    "RCPT stage": "RCPT 阶段",
    "Rate Limits": "速率限制",
    "Rules": "规则",
    "SMTP": "SMTP",
    "SPF": "SPF",
    "Scheduling": "调度",
    "Scores": "评分",
    "Scripting": "脚本",
    "Sender Authentication": "发件人认证",
    "Session Limits": "会话限制",
    "Sharing": "共享",
    "Signatures": "签名",
    "Spam traps": "垃圾邮件陷阱",
    "Sponsor": "赞助",
    "Storage Quota": "存储配额",
    "Stores": "存储",
    "Strategies": "策略",
    "System": "系统",
    "System Scripts": "系统脚本",
    "TLS": "TLS",
    "Trusted domains": "可信域名",
    "Two-factor Auth": "双因素认证",
    "URL Redirectors": "URL 重定向",
    "User Scripts": "用户脚本",
    "Virtual Queues": "虚拟队列",
    "Web Sockets": "WebSocket",
    "WebDAV": "WebDAV",
    "Webhooks": "Webhooks",
}

# Sort by length descending to prevent partial matches
sorted_translations = sorted(translations.items(), key=lambda x: len(x[0]), reverse=True)

src_dir = "src"
modified_count = 0

for root, dirs, files in os.walk(src_dir):
    for fname in files:
        if not fname.endswith(".rs"):
            continue
        filepath = os.path.join(root, fname)
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()

        original = content

        for eng, zh in sorted_translations:
            content = content.replace(f'.label("{eng}")', f'.label("{zh}")')
            content = content.replace(f'.title("{eng}")', f'.title("{zh}")')
            content = content.replace(f'.create("{eng}")', f'.create("{zh}")')

        if content != original:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"Modified: {filepath}")
            modified_count += 1

print(f"\nDone! Modified {modified_count} files.")
